---
- name: 'Install dependencies'
  tags: ['java', 'packages']
  sudo: 'yes'
  apt: >
    pkg={{ item }}
    update_cache=yes
  with_items:
    - 'python-software-properties'
    - 'python-apt'
    - 'debconf'
    - 'debconf-utils'

- name: 'Add OpenJDK PPA for latest JDK'
  tags: ['java', 'packages']
  sudo: 'yes'
  apt_repository: 'repo=ppa:openjdk-r/ppa'

- name: 'Install JDK'
  tags: ['java', 'packages']
  sudo: 'yes'
  apt: >
    pkg={{ item }}
    update_cache={{ jdk_update_apt_cache }}
  with_items:
    - 'openjdk-{{ jdk_version }}-jdk'
